name: Run Tests in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unit Tests
        working-directory: ./docker
        run: |
          ./run.sh -c "python3 -m unittest discover -s src -p '*_test.py'"

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Linter & Formatters
        working-directory: ./docker
        run: |
          ./run.sh -c "~/qtensor/src/linter.sh"
