name: CI Pipeine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unit Tests
        working-directory: ./docker
        run: |
          ./run.sh -s qtensor_dev_no_gpu -c "python3 -m unittest discover -s src -p '*_test.py'"

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          cache: pip

      # Install newer version of pre-commit once docformatter is updated to 1.7.6
      # https://github.com/PyCQA/docformatter/issues/302
      - name: Install python packages
        run: pip install pre-commit==2.20.0

      - name: Lint
        run: pre-commit run --all-files --verbose --show-diff-on-failure
